---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
    worker_connections  10240;
    }
    http {
      server {
      listen       80;
      server_name  localhost;
      location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        }
      }
    }

  private.conf: |
    user1:$apr1$rqtc1hjx$V02eLeTHZF9b1Ab9MR/VV1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
#        - mountPath: /etc/nginx
#          name: auth-nginx
        env:
        - name: nginx-username
          valueFrom:
            secretKeyRef:
              name: auth-basic
              key: username
        - name: nginx-password
          valueFrom:  
            secretKeyRef:
              name: auth-basic
              key: password
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf 
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: private.conf
            path: .htpasswd

---
apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-basic
type: kubernetes.io/basic-auth
stringData:
  username: user1
  password: password1